name: 'shell Test'
description: 'shell test'
runs:
  using: 'composite'
  steps:
    -
      run: pwd
      shell: bash
    -
      run: ./.github/actions/shell/run4.sh
      shell: bash
    -
      run: ./.github/actions/shell/run4.sh
      shell: bash

    - 
      name: commit
      uses: stefanzweifel/git-auto-commit-action@v4
